name: Flutter CI

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    name: Analyze and Test Flutter App
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'  # You can use stable or your version

      - name: Install dependencies
        run: flutter pub get

      - name: Run analyzer (lint)
        run: flutter analyze

      - name: Run tests (if any)
        run: flutter test
